### ISSUE TITLE
Check that petalinux deploys to the zybos

### ISSUE THREAD

**Issue by callummccoll** [mipalgu/zybo_ps_base#1] opened 2023-05-08 04:36 UTC

**Comment by Karan-Gspace** [comment] 2023-05-08 04:41
Check Environment Status update with Morgan

**Comment by blaisekuo** [comment] 2023-05-18 10:13
https://gilmourspace.sharepoint.com/sites/GSATDaquanta-Griffith/_layouts/15/Doc.aspx?sourcedoc={5801881d-e303-4cc7-9dfb-11db1dfb24ae}&action=edit&wd=target%28ARM7%20Dev.one%7C5f4c2207-7f3d-45b7-953e-86e37d31f95e%2F[Petalinux](onenote:https://gilmourspace.sharepoint.com/sites/GSATDaquanta-Griffith/Shared%20Documents/Griffith/GOATS/GOATS%20Development/ARM7%20Dev.one#Petalinux&section-id=5f4c2207-7f3d-45b7-953e-86e37d31f95e&page-id=aa35f358-91a3-4bce-8acd-21a06f8700c4&end)%7Caa35f358-91a3-4bce-8acd-21a06f8700c4%2F%29&wdorigin=703

Used Petalinux tools version 2022.1

Used Zybo BSP version 2022.1

Loaded a Demo image with 5.15.19-xilinx-v2022.1

Linux Petalinux-2022 5.15.19-xilinx-v2022.1 #1 SMP PREEMPT Wed Jul 20 20:30:06 UTC 2022 armv7l GNU/Linux

Demo image uses a Pmod Cam. Next task, remove that config and change it with the Pmod CAN.

**Comment by Morgan2010** [comment] 2023-05-21 23:36
Due to the corrupted state of this repo, I have created a second repo [zybo](https://github.com/mipalgu/zybo) with the following PL configuration from [zybo_pl_base](https://github.com/mipalgu/zybo_pl_base):

CAN0: JF9 and JF10,
CAN1: JF4 and JF1,
SPI0: JB PMOD (see SPI CAN for pinouts).

The following hardware controllers are also enabled as per the manufacturer configuration: QSPI Flash, Enet0, USB0, SD0 and UART1.

I have also enabled 1 TTC (through EMIO) and all remaining GPIO through EMIO. All remaining controllers are disabled.

Petalinux is installed and the CAN interfaces have been tested with the shields. I can confirm that CAN traffic is being transmitted & received with correct acknowledgements. The arty on the other end can inspect the CAN packets as they come in.

I have also installed the necessary libraries to support swift deployment. We need to cross-compile swift again using this image as the sysroot. All future versions of swift should be cross compiled with the libraries in this repository due to the new version of the petalinux tools.

This progress should be enough to close this issue.

**Comment by blaisekuo** [comment] 2023-05-22 05:32
@Morgan2010 is this correct?

To build this project using the petalinux tools (using version 2022.1):

1. pulled zybo repo.
2. cd into zybo repo dir, 
 
create a petalinux project with the zybo bsp from [zybo bsp](https://github.com/Digilent/Zybo-Z7/releases/tag/20%2FPetalinux%2F2022.1-1?_ga=2.69734032.1064577041.1684303995-88482440.1682646203)

run:
petalinux-create -t project -s path-to-bsp

3.  run petalinux-build

**Comment by Morgan2010** [comment] 2023-05-22 05:43
You shouldn't have to do petalinux-create. You just need to clone it and run petalinux-build.

**Comment by callummccoll** [comment] 2023-05-30 04:11
Waiting to complete the petalinux-package

**Comment by LewisKrygger** [comment] 2023-06-06 03:59
@Morgan2010  can this issue be closed?

**Closed as completed** 2023-06-28 06:54 UTC
